### ISSUE TITLE
Support metadata version 2.1

### ISSUE THREAD

**Issue by RayeN** [yola/yolapi#52]
Right now we don't support it.  And as result `Django == 2.0.4` cannot be uploaded:

```
[2018-04-20 13:36:46,072: ERROR/ForkPoolWorker-1] Unknown Metadata-Version: 2.1
Traceback (most recent call last):
  File "/srv/yolapi/live/yolapi/importer/tasks.py", line 54, in import_requirement
    _import_source(dist.location, tmpdir, recurse)
  File "/srv/yolapi/live/yolapi/importer/tasks.py", line 94, in _import_source
    fields = metadata_fields(metadata_version)
  File "/srv/yolapi/live/yolapi/pypi/metadata.py", line 5, in metadata_fields
    raise ValueError("Unknown Metadata-Version: %s" % metadata_version)
ValueError: Unknown Metadata-Version: 2.1
```

**Comment by jamesodo** [comment]
Reopening to add the new fields mentioned in https://github.com/yola/yolapi/pull/53#issuecomment-384834861
